all:
  vars:
    env: dev
    aws_region: us-east-1
    aws_account_id: "620958830769"
    cluster_name: "eks-devopsproject-cluster"
    
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
