apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - 00-namespace.yaml
  - ecommerce-ui.yaml
  - product-catalog.yaml
  - order-management.yaml
  - product-inventory.yaml
  - profile-management.yaml
  - shipping-and-handling.yaml
  - team-contact-support.yaml
  - ingress.yaml

commonLabels:
  managed-by: argocd
  app.kubernetes.io/part-of: ecommerce
