apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

bases:
  - ../../base

# Labels espec√≠ficos da v1
commonLabels:
  version: v1
  environment: production

# Garantir que os pods tenham label version: v1
patches:
  - target:
      kind: Deployment
      name: ecommerce-ui
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/version
        value: v1
      - op: add
        path: /spec/template/metadata/labels/version
        value: v1
  - target:
      kind: Service
      name: ecommerce-ui
    patch: |-
      - op: add
        path: /spec/selector/version
        value: v1
